name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: classic
architectures:
  - build-on: amd64

apps:
  flutter:
    command: flutter.sh
    environment:
      PATH: ${SNAP}/usr/bin:${SNAP}/bin:$PATH
      GIT_EXEC_PATH: ${SNAP}/usr/lib/git-core
      GIT_CONFIG_NOSYSTEM: 1
      CURL_CA_BUNDLE: /snap/core18/current/etc/ssl/certs/ca-certificates.crt
      GIT_SSL_CAINFO: /snap/core18/current/etc/ssl/certs/ca-certificates.crt
      CPLUS_INCLUDE_PATH: ${SNAP}/usr/include/${SNAPCRAFT_ARCH_TRIPLET}/c++/8:${SNAP}/usr/include/c++/8:${SNAP}/usr/include:${SNAP}/usr/include/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/include/c++/8
      LIBRARY_PATH: ${SNAP}/usr/lib/gcc/${SNAPCRAFT_ARCH_TRIPLET}/8:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib
      #C_INCLUDE_PATH: ${SNAP}/usr/include:${SNAP}/usr/include/${SNAPCRAFT_ARCH_TRIPLET}
      #CPPFLAGS: '${CPPFLAGS} -I${SNAP}/usr/include/c++/8 -I${SNAP}/usr/include ${CPPFLAGS}'
      #CFLAGS: '${CFLAGS} -I${SNAP}/usr/include/c++/8 -I${SNAP}/usr/include ${CFLAGS}'
      LDFLAGS: '${LDFLAGS} -L${SNAP}/usr/lib/gcc/${SNAPCRAFT_ARCH_TRIPLET}/8 -L${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET} -L${SNAP}/usr/lib/ ${LDFLAGS}'
      PKG_CONFIG_PATH: /snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/share/pkgconfig:/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:$PKG_CONFIG_PATH:/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
    stage-packages:
      - jq
      - xz-utils
      - git
      - curl
      - unzip
      - clang
      - libstdc++-8-dev
      - cmake
      - ninja-build
      - rsync
      - libglu1-mesa
      - libgtk-3-dev
      - pkg-config
      - libc6
      - libc-bin
      - patchelf

    prime:
      - -lib32
      - -libx32
      - -usr/lib32
      - -usr/libx32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*
      - -usr/share/doc
      - -usr/share/man
      - -usr/include/c++/7*
      - -usr/include/*/c++/7*

  # Fix pkgconfig files
  pkgconfig:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
        sed -i 's#prefix=$SNAPCRAFT_STAGE#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current#' $PC
        sed -i 's#prefix = /usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#prefix=/usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#original_prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#original_prefix=/usr#' $PC

        sed -i 's#libdir=/usr#libdir=${prefix}#' $PC
        sed -i 's#libdir=/lib#libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib#' $PC

        sed -i 's#exec_prefix=/usr#exec_prefix=${prefix}#' $PC
        sed -i 's#includedir=/usr#includedir=${prefix}#' $PC
        sed -i 's#sysconfdir=/etc#sysconfdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/etc#' $PC

        sed -i 's#/usr/#/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/#g' $PC
        sed -i 's#/etc/#/snap/$SNAPCRAFT_PROJECT_NAME/current/etc/#g' $PC
      done

  # Fix linker files
  linker:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for so in usr/lib/x86_64-linux-gnu/libc.so usr/lib/x86_64-linux-gnu/libpthread.so usr/lib/x86_64-linux-gnu/libm.so
      do
        sed -i "${so}" \
            -e "s# /lib/x86_64-linux-gnu# /snap/$SNAPCRAFT_PROJECT_NAME/current/lib/x86_64-linux-gnu#g" \
            -e "s# \(/usr/lib/x86_64-linux-gnu/.*\)# /snap/$SNAPCRAFT_PROJECT_NAME/current\1#g"
      done
